### ISSUE TITLE
cannot import 'SteadierCom'

### ISSUE THREAD

**Issue by roschlec** [cdanielmachado/designmc#2]
Hi Daniel,

I am keen to try DesignMC but when I want to check the documentation `designmc -h` I get the following error about 'SteadierCom' from `reframed:`

```
designmc -h
Traceback (most recent call last):
  File "/opt/anaconda3/envs/metabolic/bin/designmc", line 5, in <module>
    from designmc.cli import main
  File "/opt/anaconda3/envs/metabolic/lib/python3.8/site-packages/designmc/__init__.py", line 7, in <module>
    from .designmc import design
  File "/opt/anaconda3/envs/metabolic/lib/python3.8/site-packages/designmc/designmc.py", line 2, in <module>
    from reframed import Community, SteadierCom, FBA
ImportError: cannot import name 'SteadierCom' from 'reframed' (/opt/anaconda3/envs/metabolic/lib/python3.8/site-packages/reframed/__init__.py)
```

The dependencies look fine to me:
```
Requirement already satisfied: designmc in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (0.1.0)
Requirement already satisfied: pandas in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (from designmc) (1.4.3)
Requirement already satisfied: reframed in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (from designmc) (1.2.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (from pandas->designmc) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (from pandas->designmc) (1.23.1)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (from pandas->designmc) (2022.1)
Requirement already satisfied: scipy in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (from reframed->designmc) (1.9.0)
Requirement already satisfied: sympy in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (from reframed->designmc) (1.10.1)
Requirement already satisfied: python-libsbml in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (from reframed->designmc) (5.19.6)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas->designmc) (1.16.0)
Requirement already satisfied: mpmath>=0.19 in /opt/anaconda3/envs/metabolic/lib/python3.8/site-packages (from sympy->reframed->designmc) (1.2.1)
```

I hope you can have a look at it or maybe give me some directions on how to fix it. Thank you for your help.

Cheers,
Rudolf

**Comment by cdanielmachado** [comment]
Hi Rudolf,

You need to downgrade reframed to version 1.1.0.

Best regards,
Daniel

**Comment by roschlec** [comment]
Amazing, thank you! That solved the problem in no time.

Cheers,
Rudolf
